# Generated by Django 3.2.9 on 2022-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=100)),
                ('telefoneCliente', models.CharField(max_length=16)),
                ('emailcliente', models.EmailField(max_length=254)),
            ],
        ),
    ]
