# Generated by Django 3.2.9 on 2022-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=100)),
                ('valorProduto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidadeProduto', models.IntegerField()),
                ('dataCompra', models.DateField()),
            ],
        ),
    ]
