# Generated by Django 3.2.9 on 2022-11-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFornec', models.CharField(max_length=100)),
                ('telefoneFornec', models.CharField(max_length=16)),
                ('emailFornec', models.EmailField(max_length=254)),
                ('regiao', models.CharField(max_length=30)),
            ],
        ),
    ]
